version: '3.3'

services:
   db:
     image: postgres:11.0
     environment:
      POSTGRES_PASSWORD: 048fa3d1
     restart: always
   #   volumes:
   #     - db_data:/var/lib/mysql

   local:
      build: .
      ports:
         - "9999:9999"
      environment:
         CHOOSECAT_PORT: 9999
         POSTGRES_PASSWORD: 048fa3d1
      volumes:
      - ./bash_history:/root/.bash_history
      - ./:/app
      depends_on:
      - db


   # wordpress:
   #   image: wordpress:latest
   #   ports:
   #     - "9999:80"
   #   restart: always
   #   environment:
   #     WORDPRESS_DB_HOST: db:3306
   #     WORDPRESS_DB_USER: wordpress
   #     WORDPRESS_DB_PASSWORD: wordpress
# volumes:
#     db_data: