version: '3.3'

services:
   db:
      image: postgres:11.0
      environment:
         POSTGRES_PASSWORD: 048fa3d1
      restart: always
      ports:
      - "5432:5432"
   #   volumes:
   #     - db_data:/var/lib/mysql

   local:
      build: .
      ports:
         - "9999:9999"
      environment:
         CHOOSECAT_PORT: 9999
         POSTGRES_PASSWORD: 048fa3d1
      volumes:
      - ./bash_history:/root/.bash_history
      - ./:/app
      depends_on:
      - db
